config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :users do
    resources :shopping_cart_items
  end
  get 'control-panel', to: 'users#show'
  resources :products, :patterns, :events
  get 'faq', to: 'pages#faq'
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
    
end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
    
end

app/models/product.rb
class Product < ActiveRecord::Base
    
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ActiveRecord::Base
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            ContactMailer.contact_email(name, email, body).deliver
            flash[:success] = "Message sent."
            redirect_to new_contact_path
        else
            flash[:danger] = @contact.errors.full_messages.join(", ")
            redirect_to new_contact_path
        end
    end
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)
        end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, except: [:show, :index]
    before_action :only_admin_user, except: [:show, :index]
   
   def new
      @event = Event.new 
   end
   
   def edit
        @event = Event.find(params[:id]) 
   end
   
   def create
      @event = Event.new( event_params )
      if @event.save
          flash[:success] = "Event created"
          redirect_to events_path
      else
          flash[:error] = "Event creation failed"
          render action: :new
      end
   end
   
   def show
        @event = Event.find(params[:id]) 
   end
   
   def update
        @event = Event.find(params[:id])
        if @event.update_attributes( event_params )
            flash[:success] = "Event updated"
            redirect_to event_path(id: params[:id])
        else
            flash[:error] = "Event update failed"
            render action: :show
        end
   end
   
   def destroy
        Event.find(params[:id]).destroy
        redirect_to events_path
   end
   
   def index
        @events = Event.all 
   end
   
   private
        def only_admin_user
           @user = current_user
           redirect_to(root_url) unless @user.admin
        end
        def event_params
           params.require(:event).permit(:name, :startdate, :details) 
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        if user_signed_in?
            @admin = current_user.admin
        end
    end
    
    def news
    end
    
    def faq
    end
    
    def about
    end
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
   before_action :authenticate_user!, except: [:show, :index]
   before_action :only_admin_user, except: [:show, :index]
   
   def new
      @pattern = Pattern.new 
   end
   
   def edit
      @pattern = Pattern.find(params[:id]) 
   end
   
   def create
      @pattern = Pattern.new( pattern_params )
      if @pattern.save
          flash[:success] = "Pattern Created"
          redirect_to patterns_path
      else
          flash[:error] = 'Pattern creation failed'
          render action: :new
      end
   end
   
   def show
      @pattern = Pattern.find(params[:id]) 
   end
   
   def update
        @pattern = Pattern.find(params[:id])
        if @pattern.update_attributes(pattern_params)
            flash[:success] = "Pattern updated"
            redirect_to pattern_path(id: params[:id])
        else
            flash[:error] = "Pattern update failed"
            render action: :show
        end
   end
   
   def destroy
      Pattern.find(params[:id]).destroy
      redirect_to patterns_path
   end
   
   def index
        @patterns = Pattern.all 
   end
   
   private
      def only_admin_user
           @user = current_user
           redirect_to(root_url) unless @user.admin
      end
      def pattern_params
        params.require(:pattern).permit(:name) 
      end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   before_action :authenticate_user!, except: [:show, :index]
   before_action :only_admin_user, except: [:show, :index]
   
   def new
      @product = Product.new
   end 
   
   def edit
      @product = Product.find(params[:id])
   end
   
   def create
      @product = Product.new( product_params )
      if @product.save
         flash[:success] = "Product created"
         redirect_to products_path
      else
         flash[:notice] = "Product creation failed"
         redner action: :new
      end
   end
   
   def show
      @product = Product.find(params[:id])
      @shopping_cart_item = ShoppingCartItem.new
   end
   
   def update
      @product = Product.find(params[:id])
      if @product.update_attributes( product_params )
         flash[:success] = "Product updated"
         redirect_to product_path(id: params[:id])
      else
         flash[:error] = "Product update failed"
         render action: :show
      end
   end
   
   def destroy
      Product.find(params[:id]).destroy
      redirect_to products_path
   end
   
   def index
      @products = Product.all #Product.includes() TODO
   end
   
   private
       def only_admin_user
           @user = current_user
           redirect_to(root_url) unless @user.admin
       end
       
       def product_params
          params.require(:product).permit(:name, :price, :picture_url, :comments, :christmas, :clothing, :in_stock)
       end
end

app/controllers/shopping_cart_items_controller.rb
class ShoppingCartItemsController < ApplicationController
    def create
       @shopping_cart_item = ShoppingCartItem.new(cart_item_params)
       @shopping_cart_item.product_id = params[:id]
       @shopping_cart_item.user_id = current_user.id
       # get cost
    #   @shopping_cart_item.cost = Product.find(params[:id]).price
       if @shopping_cart_item.save
           flash[:success] = "Item added to cart"
           redirect_to products_path
       else
           flash[:error] = "Couldn't add to cart"
           redirect_to root_path
       end
    end
    
    def update
       @shopping_cart_item = ShoppingCartItem.find(params[:id])
       if @shopping_cart_item.update_attributes(cart_item_params)
           flash[:success] = "Cart item updated"
           redirect_to user_cart_items_path(user_id: current_user.id)
       else
           flash[:error] = "Cart item upadte failed"
           redirect_to user_cart_items_path(user_id: current_user.id)
       end
    end
    
    def destroy
        ShoppingCartItem.find(params[:id]).destroy
        redirect_to user_shopping_cart_items_path(user_id: current_user.id)
    end
    
    def index
       @shopping_cart_items = ShoppingCartItem.where("user_id = ?", current_user.id) 
    end
    
    private
        def cart_item_params
           params.require(:shopping_cart_item).permit(:user_id, :product_id, :count, :cost) 
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :only_admin_user
    
    
   def show
       @user = User.find( current_user.id)
   end
   
   private
       def only_admin_user
           @user = current_user
           redirect_to(root_url) unless @user.admin
       end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Brazil Boutique Contact Us</h3>
    <div class="col-md-4 col-md-offset-4">
        <div class="well">
            <%= form_for @contact do |f| %>
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :email %>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :comments %>
                <%= f.text_area :comments, class: 'form-control' %>
              </div>
              <%= f.submit 'Submit', class: 'btn btn-default' %>
            <% end %>
        </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="well">
                <h1 class="text-center">Edit News/Event</h1>
                <%= form_for @event, url: event_url do |f| %>
                    <div class="form-group">
                        <%= f.label :name %>
                        <%= f.text_field :name, class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= f.label :startdate %>
                        <%= f.datetime_field :startdate, class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= f.label :details %>
                        <%= f.text_area :details, class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= f.submit :submit, class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/events/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">News/Events</h1>
            <% @events.each do |event| %>
                <div class="well">
                    <%= link_to event_path(id: event.id) do %>
                        <h3><%= event.name %></h3>
                    <% end %>
                    <h5>Starts at: <%= event.startdate %></h5>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/events/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="well">
                <h1 class="text-center">New News/Event</h1>
                <%= form_for @event, url: events_url do |f| %>
                    <div class="form-group">
                        <%= f.label :name %>
                        <%= f.text_field :name, class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= f.label :startdate %>
                        <%= f.datetime_field :startdate, class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= f.label :details %>
                        <%= f.text_area :details, class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= f.submit :submit, class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/events/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="well">
                <h3><%= @event.name %></h3>
                <h5>Starts at: <%= @event.startdate %></h5>
                <div class="well">
                    <p><%= @event.details %></p>
                </div>
                <% if user_signed_in? && current_user.admin %>
                    <%= link_to edit_event_path(params[:id]), class: "btn btn-primary" do %>
                        <i class="fa fa-edit"></i>
                    <% end %>
                    <%= link_to event_path(params[:id]), method: :delete, class: "btn btn-danger" do %>
                        <i class="fa fa-trash"></i>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bbapp</title>
    <%= csrf_meta_tags %>

    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-gift"></i>
            Brazil Boutique
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Products", products_path %></li>
            <li><%= link_to "Patterns", patterns_path %></li>
            <li><%= link_to "News/Events", events_path %></li>
          </ul>
          <div class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "btn btn-default navbar-btn" %>
            <% end %>
            <% if user_signed_in? && current_user.admin %>
              <%= link_to "Control Panel", control_panel_path, class: "btn btn-default navbar-btn" %>
            <% end %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <%= link_to user_shopping_cart_items_path(user_id: current_user.id), class: "btn btn-primary navbar-btn" do %>
              <i class="fa fa-shopping-cart"></i>
            <% end %>
            <li><%= link_to "F.A.Q.", faq_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <div class="container flash-container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    
    <%= yield %>
    
  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
    <h1>Brazil Boutique About Page</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, 
    aspernatur ipsam ad temporibus ipsum tempore dicta obcaecati tempora 
    laboriosam suscipit dolores ullam vero itaque exercitationem officia 
    cum odio ducimus similique.</p>
</div>

app/views/pages/faq.html.erb
<div class="container text-center">
    <h1>Brazil Boutique FAQ</h1>
    <h3>What is question one?</h3>
    <p>The answer as we see it is as follows</p>
    <h3>What is the second question?</h3>
    <p>The answer is Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
    Ipsum, perspiciatis, nesciunt, repellendus, aspernatur totam sapiente optio 
    ipsam quibusdam nulla accusamus incidunt officiis iusto maiores sint dolore 
    voluptatibus esse maxime mollitia?</p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
    <%= image_tag("BrazilBoutiqueBannerAlpha.png", size: "548x320", alt:"Brazil Boutique") %>
    <h3>We make personalized gifts, decor, clothing and more!</h3>
</div>

app/views/pages/products.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>BB Products Page</h1>
            <% @products.each do |product| %>
                <div class="well">
                    <h2 class='text-center'><%= product.name %></h2>
                    <% if !(product.picture_url == "#") %>
                        <%= image_tag product.picture_url, class: 'product-index-picture' %>
                    <% end %>
                    <h5>$<%= product.price %></h5>
                    <p><%= product.comments %></p>
                    <% if product.in_stock %>
                        <i class='fa fa-battery-full'></i>
                        <h5>In Stock</h5>
                    <% end %>
                    <% if product.christmas %>
                        <i class='fa fa-tree'></i>
                    <% end %>
                    <% if product.clothing %>
                        <i class='fa fa-black-tie'></i>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/patterns/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="well">
                <h1 class="text-center">Edit Pattern</h1>
                <%= form_for @pattern, url: pattern_url do |f| %>
                    <div class="form-group">
                        <%= f.label :name %>
                        <%= f.text_field :name, class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= f.submit :submit, class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/patterns/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h1 class="text-center">Pattern Index</h1>
            <% @patterns.each do |pattern| %>
                <div class="well">
                    <%= link_to pattern_path(id: pattern.id) do %>
                        <h3><%= pattern.name %></h3>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/patterns/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="well">
                <h1 class="text-center">New Pattern</h1>
                <%= form_for @pattern, url: patterns_url do |f| %>
                    <div class="form-group">
                        <%= f.label :name %>
                        <%= f.text_field :name, class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= f.submit :submit, class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/patterns/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="well">
                <h2 class="text-center"><%= @pattern.name %></h2>
            </div>
            <% if user_signed_in? && current_user.admin %>
                <%= link_to edit_pattern_path(params[:id]), class: "btn btn-primary" do %>
                    <i class="fa fa-edit"></i>
                <% end %>
                <%= link_to pattern_path(params[:id]), method: :delete, class: "btn btn-danger" do %>
                    <i class="fa fa-trash"></i>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/products/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="text-center">Edit Product</h2>
            <div class="well">
                <%= form_for @product, url: product_path do |f| %>
                  <div class="field form-group">
                    <%= f.label :name %><br />
                    <%= f.text_field :name, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :price %><br />
                    <%= f.text_field :price, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :picture_url %><br />
                    <%= f.text_field :picture_url, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :comments %><br />
                    <%= f.text_area :comments, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :christmas %><br />
                    <%= f.radio_button :christmas, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :clothing %><br />
                    <%= f.radio_button :clothing, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :in_stock %><br />
                    <%= f.radio_button :in_stock, class: 'form-control' %>
                  </div>
                
                  <div class="actions form-group">
                    <%= f.submit "Update", class: 'btn btn-success' %>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/products/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>BB Products Page</h1>
            <% @products.each do |product| %>
                <div class="well">
                    <%= link_to product_path(id: product.id) do %>
                        <h2 class='text-center'><%= product.name %></h2>
                    <% end %>
                    <% if !(product.picture_url == "#") %>
                        <%= image_tag product.picture_url, class: 'product-index-picture' %>
                    <% end %>
                    <h5>$<%= product.price %></h5>
                    <p><%= product.comments %></p>
                    <% if product.in_stock %>
                        <i class='fa fa-battery-full'></i>
                        <h5>In Stock</h5>
                    <% end %>
                    <% if product.christmas %>
                        <i class='fa fa-tree'></i>
                    <% end %>
                    <% if product.clothing %>
                        <i class='fa fa-black-tie'></i>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/products/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h2 class="text-center">New Product</h2>
            <div class="well">
                <%= form_for @product, url: products_path do |f| %>
                  <div class="field form-group">
                    <%= f.label :name %><br />
                    <%= f.text_field :name, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :price %><br />
                    <%= f.text_field :price, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :picture_url %><br />
                    <%= f.text_field :picture_url, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :comments %><br />
                    <%= f.text_area :comments, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :christmas %><br />
                    <%= f.radio_button :christmas, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :clothing %><br />
                    <%= f.radio_button :clothing, class: 'form-control' %>
                  </div>
                  <div class="field form-group">
                    <%= f.label :in_stock %><br />
                    <%= f.radio_button :in_stock, class: 'form-control' %>
                  </div>
                
                  <div class="actions form-group">
                    <%= f.submit "Create", class: 'btn btn-success' %>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/products/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="well">
                <h2 class='text-center'><%= @product.name %></h2>
                <% if !(@product.picture_url == "#") %>
                    <%= image_tag @product.picture_url, class: 'product-index-picture' %>
                <% end %>
                <h5>$<%= @product.price %></h5>
                <p><%= @product.comments %></p>
                <% if @product.in_stock %>
                    <i class='fa fa-battery-full'></i>
                    <h5>In Stock</h5>
                <% end %>
                <% if @product.christmas %>
                    <i class='fa fa-tree'></i>
                <% end %>
                <% if @product.clothing %>
                    <i class='fa fa-black-tie'></i>
                <% end %>
                <% if user_signed_in? %>
                    <%= form_for @shopping_cart_item, url: user_shopping_cart_items_path(current_user.id) do |f| %>
                        <div class="field form-group">
                            <%= f.label :quantity %>
                            <%= f.number_field :count %>
                        </div>
                        <div class="actions form-group">
                            <%= f.submit "Add to cart", class: "btn btn-primary" %>
                        </div>
                    <% end %>
                <% end %>
                <% if user_signed_in? && current_user.admin %>
                    <%= link_to edit_product_path(params[:id]), class: "btn btn-primary" do %>
                        <i class="fa fa-edit"></i>
                    <% end %>
                    <%= link_to product_path(params[:id]), method: :delete, class: "btn btn-danger" do %>
                        <i class="fa fa-trash"></i>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/shopping_cart_items/index.html.erb
<div class="contianer">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1 class="text-center">My Cart</h1>
            <% @shopping_cart_items.each do |cart_item| %>
                <div class="well row">
                    <div class="col-sm-3">
                        <h4>ID: <%= cart_item.id.to_s %></h4>
                    </div>
                    <div class="col-sm-3">
                        <h4>Prod ID: <%= cart_item.product_id %></h4>
                    </div>
                    <div class="col-sm-3">
                        <h4>Count: <%= cart_item.count %></h4>
                    </div>
                    <div class="col-sm-3">
                        <%= link_to user_shopping_cart_item_path(user_id: current_user.id, id: cart_item.id), method: :delete, class: "btn btn-danger" do %>
                            <i class="fa fa-trash"></i>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class='row'>
        <div class="col-md-6 col-md-offset-3">
            <div class="well">
                <h1>Admin Control Panel</h1>
                <%= link_to "New Product", new_product_path, class: "btn btn-default" %>
                <%= link_to "New Pattern", new_pattern_path, class: "btn btn-default" %>
                <%= link_to "New Event/News", new_event_path, class: "btn btn-default" %>
            </div>
        </div>
    </div>
</div>